gText_Birch_Welcome::
	.string "Hello! Welcome to the POKéMON Smoke\n"
	.string "Demo.\p"
	.string "I'm a POKéMON PROFESSOR who will be\n"
	.string "replaced, so I'm not important.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "But look at this cool POKéMON.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "But you're not here to listen to me blab\n"
	.string "on all day.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Let's get to know you!$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN}, who's going on an\n"
	.string "adventure.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\n"
	.string "Go have some fun!\p"
	.string "$"
